@startuml
!include ../style.puml

participant ":Storage" as S STORAGE_COLOR
participant "<<Class>>\n:CaseManager" as CM CASEFILE_COLOR
participant ":Case" as C CASEFILE_COLOR
participant "<<Class>>\n:Settings" as SET UI_COLOR

-[MAIN_COLOR]> S : saveToFile()
activate S STORAGE_COLOR_T1

    S -[STORAGE_COLOR]> SET : get each date format
    activate SET UI_COLOR_T1
    return

    S -[STORAGE_COLOR]> CM : getCaseManager
    activate CM CASEFILE_COLOR_T1
    return caseList

    loop for cases in caseList
        S -[STORAGE_COLOR]> C : getSaveString()
        activate C CASEFILE_COLOR_T1
        return save string
    end loop

return

@enduml